name: post-from-ios
on:
  workflow_dispatch:
    inputs:
      content:
        description: "content of the post"
        required: true
        type: string
      title:
        description: "title of the post"
        required: true
        type: string
jobs:
  post-from-ios:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "weijianduan0302@gmail.com"
      - name: create new post
        run: |
          date=$(date '+%Y-%m-%d')
          content="${{ inputs.content }}"
          title="${{ inputs.title }}"

          post_file="./_posts/${date}-${title}.md"

          cat <<EOF > "${post_file}"
          ---
          layout: post
          title: ${title}
          date: $(date +"%Y-%m-%d %H:%M %z")
          ---
          ${content}
          EOF

          commit_message="add post ${title}"
          git add "${post_file}"
          git commit -m "${commit_message}"
          git push origin HEAD:main
